name: portalsapl
services:
  saplredis:
    image: redis:alpine
    container_name: saplredis
    restart: always #restart: unless-stopped
    labels:
       NAME: "saplredis"
    volumes:
      - credis_data:/data
    #ports:
    #  - "6379:6379"
    networks:
      - sapl-net
  saplsolr:
    image: solr:9.5
    restart: always
    command: bin/solr start -c -f
    container_name: saplsolr
    labels:
        NAME: "saplsolr"
    volumes:
      - csolr9_data:/var/solr
      - csolr9_configsets:/opt/solr/server/solr/configsets
    #ports:
    #  - "8983:8983"
    networks:
      - sapl-net
  sapldb:
    image: postgres:14.5-alpine
    restart: always
    container_name: saplpostgres
    labels:
        NAME: "saplpostgres"
    environment:
      POSTGRES_PASSWORD: cmj
      POSTGRES_USER: cmj
      POSTGRES_DB: cmj
      PGDATA : /var/lib/postgresql/data/
    volumes:
      - sapldb_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - sapl-net
  sapl:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: sapl
    user: "root:root"
    labels:
       NAME: "sapl"
    restart: always
    environment:
      DEBUG: 'False'
      USE_SOLR: 'True'
      SOLR_COLLECTIONS: portalcmj_cmj,portalcmj_arq
      SOLR_URL: http://solr:solr@cmjsolr:8983
      IS_ZK_EMBEDDED: 'True'
      TZ: America/Sao_Paulo
    volumes:
      - sapl_data:/var/cmjatai/cmj_data
      - sapl_media:/var/cmjatai/cmj_media
      - sapl_logs:/var/cmjatai/cmj/logs
    depends_on:
      - sapldb
      - saplredis
      - saplsolr
    ports:
      - "8003:80"
    networks:
      - cmj-net
networks:
  sapl-net:
    name: sapl-net
    driver: bridge
volumes:
  sapldb_data:
  sapl_data:
  sapl_media:
  sapl_logs:
  csolr9_data:
  csolr9_configsets:
  credis_data:
